/// ShortcutGenerator.swift
///
/// Generates Apple Shortcut (.shortcut) plist files from HomeKit automation actions
/// and manages their lifecycle in the Shortcuts app via the macOS `shortcuts` CLI.
///
/// ## Shortcuts Integration
/// Apple Shortcuts are stored as binary plist files with a specific structure containing:
/// - Workflow metadata (version, icon, client compatibility info)
/// - Array of serialized action dictionaries (WFWorkflowActions)
/// - Each action has a WFWorkflowActionIdentifier and parameters (WFWorkflowActionParameters)
///
/// ## Plist Format & Structure
/// The generated plist follows Apple's Shortcut format with:
/// - `WFWorkflowActions`: Array of action dictionaries, each representing a HomeKit
///   control action, delay, scene trigger, or comment
/// - `WFWorkflowMinimumClientVersion`: Version 900 (macOS 12+) for shortcuts CLI support
/// - `WFWorkflowIcon`: Orange home icon for easy visual identification
/// - Workflow type declarations enabling use in widgets and watchOS
///
/// ## HKA: Naming Convention
/// Generated Shortcuts are prefixed with "HKA: " to identify them as HomeKit Automator–
/// generated shortcuts. This helps distinguish them from manually created shortcuts
/// and makes them easy to locate and manage via the shortcuts CLI.
///
/// ## Workflow Overview
/// 1. Generate: Build a plist from AutomationAction objects, serialize to binary format
/// 2. Import: Use `shortcuts import` CLI (preferred) with fallback to `open` command
/// 3. Manage: Run, delete, or check existence via the macOS `shortcuts` command-line tool

import Foundation

/// Generates Apple Shortcuts from automation action lists and manages their lifecycle.
///
/// This struct provides the core functionality for converting HomeKit automation
/// definitions into executable Apple Shortcuts. The workflow is:
/// 1. `generate()` creates a .shortcut plist file with serialized HomeKit actions
/// 2. `importShortcut()` adds it to the Shortcuts app (CLI-first, with UI fallback)
/// 3. Static methods (`deleteShortcut`, `runShortcut`, `shortcutExists`) manage
///    shortcuts via the macOS shortcuts CLI for runtime operations
struct ShortcutGenerator {

    /// Generate a .shortcut file from a list of automation actions.
    ///
    /// Creates a binary plist file that can be imported into the Shortcuts app.
    /// The plist contains a workflow with the following structure:
    /// - A comment action identifying the file as HKA–generated
    /// - Optional delay actions (if delaySeconds > 0)
    /// - HomeKit device control actions or scene triggers, in order
    ///
    /// Supported action types:
    /// - Device control: sets a characteristic (e.g., brightness, power) via
    ///   `homeKitSetAction()` which uses WFWorkflowActionIdentifier `is.workflow.actions.homekit.set`
    /// - Scene triggers: activates a HomeKit scene via `sceneAction()` which uses
    ///   WFWorkflowActionIdentifier `is.workflow.actions.homekit.scene`
    /// - Delays: pauses execution via `delayAction()` using `is.workflow.actions.delay`
    ///
    /// The plist is serialized in binary format (PropertyListSerialization.binary)
    /// with version compatibility set to 900 (macOS 12+) and includes workflow
    /// metadata like icon color (orange), glyph (home icon), and supported types
    /// (NCWidget, WatchKit).
    ///
    /// - Parameters:
    ///   - name: Shortcut name (not used directly in the plist but available for context)
    ///   - actions: Array of AutomationAction objects to serialize
    ///   - outputPath: File URL where the .shortcut plist should be written
    func generate(name: String, actions: [AutomationAction], outputPath: URL) throws {
        var workflowActions: [[String: Any]] = []

        // Add a comment action identifying the source
        workflowActions.append(commentAction(
            "Generated by HomeKit Automator. Do not edit manually."
        ))

        for action in actions {
            // Insert delay if specified
            if action.delaySeconds > 0 {
                workflowActions.append(delayAction(seconds: action.delaySeconds))
            }

            // Handle scene triggers
            if action.type == "scene" {
                if let sceneUuid = action.sceneUuid, let sceneName = action.sceneName {
                    workflowActions.append(sceneAction(uuid: sceneUuid, name: sceneName))
                }
                continue
            }

            // Regular device control action
            workflowActions.append(homeKitSetAction(
                deviceUuid: action.deviceUuid,
                deviceName: action.deviceName,
                characteristic: action.characteristic,
                value: action.value
            ))
        }

        // Build the full Shortcut plist
        let shortcutDict: [String: Any] = [
            "WFWorkflowMinimumClientVersionString": "900",
            "WFWorkflowMinimumClientVersion": 900,
            "WFWorkflowClientVersion": "2612.0.4",
            "WFWorkflowIcon": [
                "WFWorkflowIconStartColor": 4274264319,  // Orange
                "WFWorkflowIconGlyphNumber": 59758         // Home icon
            ],
            "WFWorkflowActions": workflowActions,
            "WFWorkflowInputContentItemClasses": [
                "WFAppStoreAppContentItem",
                "WFArticleContentItem"
            ],
            "WFWorkflowImportQuestions": [],
            "WFWorkflowTypes": ["NCWidget", "WatchKit"],
            "WFWorkflowHasShortcutInputVariables": false
        ]

        // Serialize to plist data
        let plistData = try PropertyListSerialization.data(
            fromPropertyList: shortcutDict,
            format: .binary,
            options: 0
        )

        try plistData.write(to: outputPath, options: .atomic)
    }

    /// Import a Shortcut file into the Shortcuts app.
    ///
    /// Supports two import strategies with automatic fallback:
    /// 1. **CLI strategy (preferred)**: Uses the `shortcuts import` command (macOS 12+)
    ///    for silent, non-interactive import. This is reliable when the Shortcuts app is
    ///    properly configured and the file is valid.
    /// 2. **Open strategy (fallback)**: Invokes `/usr/bin/open` on the .shortcut file,
    ///    which launches the Shortcuts app and prompts the user to confirm the import.
    ///    Used if the CLI tool fails or is unavailable on older macOS versions.
    ///
    /// Returns true if the import succeeds via either method, false otherwise.
    ///
    /// - Parameters:
    ///   - name: Shortcut name (metadata; may be used in future for validation)
    ///   - path: File URL pointing to the .shortcut plist file
    /// - Returns: True if import succeeded, false otherwise
    func importShortcut(name: String, path: URL) async throws -> Bool {
        // Check if a shortcut with this name already exists
        if await ShortcutGenerator.shortcutExists(name: name) {
            print("⚠️  Warning: Shortcut '\(name)' already exists. It will be overwritten.")
            let deleted = await ShortcutGenerator.deleteShortcut(name: name)
            if !deleted {
                print("⚠️  Warning: Failed to delete existing shortcut '\(name)'. Import may conflict.")
            }
        }

        // Method 1: Use the `shortcuts` CLI tool (macOS 12+)
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/shortcuts")
        process.arguments = ["import", path.path]

        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError = pipe

        do {
            try process.run()
            process.waitUntilExit()

            if process.terminationStatus == 0 {
                return true
            }

            // Fallback: try opening the file (prompts user)
            return try await importViaOpen(path: path)
        } catch {
            // Fallback: try opening the file
            return try await importViaOpen(path: path)
        }
    }

    /// Fallback import: open the .shortcut file, which prompts the Shortcuts app to import it.
    ///
    /// Uses the macOS `open` command to launch the Shortcuts app with the .shortcut file.
    /// This is less reliable than the CLI import but works on older macOS versions and
    /// when the shortcuts CLI tool is unavailable or fails. The user must confirm the
    /// import in the Shortcuts app UI.
    ///
    /// - Parameter path: File URL pointing to the .shortcut plist file
    /// - Returns: True if the open command executed successfully, false otherwise
    private func importViaOpen(path: URL) async throws -> Bool {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/open")
        process.arguments = [path.path]

        try process.run()
        process.waitUntilExit()

        return process.terminationStatus == 0
    }

    /// Delete a Shortcut by name using the macOS shortcuts CLI.
    ///
    /// Executes `shortcuts delete <name>` to remove a shortcut from the Shortcuts app.
    /// This is a destructive operation and cannot be undone. The shortcuts CLI tool
    /// is available on macOS 12+. Returns false if the tool fails or is unavailable.
    ///
    /// - Parameter name: Name of the Shortcut to delete (exact match required)
    /// - Returns: True if deletion succeeded, false otherwise
    static func deleteShortcut(name: String) async -> Bool {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/shortcuts")
        process.arguments = ["delete", name]

        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError = pipe

        do {
            try process.run()
            process.waitUntilExit()
            return process.terminationStatus == 0
        } catch {
            return false
        }
    }

    /// Run a Shortcut by name using the macOS shortcuts CLI.
    ///
    /// Executes `shortcuts run <name>` to trigger a shortcut from the command line.
    /// This is commonly used to execute HomeKit automation shortcuts programmatically.
    /// The shortcuts CLI tool is available on macOS 12+. Returns false if execution fails
    /// or the tool is unavailable.
    ///
    /// - Parameter name: Name of the Shortcut to execute (exact match required)
    /// - Returns: True if execution succeeded, false otherwise
    static func runShortcut(name: String) async -> Bool {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/shortcuts")
        process.arguments = ["run", name]

        do {
            try process.run()
            process.waitUntilExit()
            return process.terminationStatus == 0
        } catch {
            return false
        }
    }

    /// Check if a Shortcut exists by name using the macOS shortcuts CLI.
    ///
    /// Executes `shortcuts list` to retrieve all installed shortcuts, then searches
    /// the output for an exact name match. This is useful for checking whether a
    /// shortcut has been previously imported before attempting to create or delete it.
    /// The shortcuts CLI tool is available on macOS 12+. Returns false if the list
    /// command fails or the tool is unavailable.
    ///
    /// - Parameter name: Name of the Shortcut to check (exact match required)
    /// - Returns: True if the shortcut exists, false otherwise
    static func shortcutExists(name: String) async -> Bool {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/shortcuts")
        process.arguments = ["list"]

        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError = Pipe()

        do {
            try process.run()
            process.waitUntilExit()

            let data = pipe.fileHandleForReading.readDataToEndOfFile()
            let output = String(data: data, encoding: .utf8) ?? ""
            return output.components(separatedBy: "\n").contains(name)
        } catch {
            return false
        }
    }

    // MARK: - Shortcut Action Builders

    /// Build a HomeKit device control action (WFWorkflowActionIdentifier: is.workflow.actions.homekit.set).
    ///
    /// Creates a dictionary representing a HomeKit "Set Device" action that controls
    /// a characteristic (e.g., brightness, power state, temperature) on a device.
    /// The action parameters include:
    /// - `WFHomeAccessory`: Device identifier dict with `id` (UUID) and `name` (display name)
    /// - `WFHomeCharacteristic`: Characteristic name (e.g., "Brightness", "Power", "TargetTemperature")
    /// - `WFHomeValue`: The value to set (bool, int, double, or string depending on characteristic type)
    ///
    /// - Parameters:
    ///   - deviceUuid: HomeKit device UUID for internal identification
    ///   - deviceName: Human-readable device name (displayed in Shortcuts)
    ///   - characteristic: HomeKit characteristic name to control
    ///   - value: AnyCodableValue (bool, int, double, or string) to set
    /// - Returns: Action dictionary for serialization into WFWorkflowActions
    private func homeKitSetAction(
        deviceUuid: String,
        deviceName: String,
        characteristic: String,
        value: AnyCodableValue
    ) -> [String: Any] {
        var params: [String: Any] = [
            "WFHomeAccessory": [
                "id": deviceUuid,
                "name": deviceName
            ] as [String: Any],
            "WFHomeCharacteristic": characteristic
        ]

        switch value {
        case .bool(let b):
            params["WFHomeValue"] = b
        case .int(let i):
            params["WFHomeValue"] = i
        case .double(let d):
            params["WFHomeValue"] = d
        case .string(let s):
            params["WFHomeValue"] = s
        default:
            params["WFHomeValue"] = "\(value)"
        }

        return [
            "WFWorkflowActionIdentifier": "is.workflow.actions.homekit.set",
            "WFWorkflowActionParameters": params
        ]
    }

    /// Build a HomeKit scene trigger action (WFWorkflowActionIdentifier: is.workflow.actions.homekit.scene).
    ///
    /// Creates a dictionary representing a HomeKit "Activate Scene" action that triggers
    /// a predefined HomeKit scene. Scenes are groups of device controls bundled together
    /// (e.g., "Good Night" scene that locks doors and turns off lights).
    /// The action parameters include:
    /// - `WFHomeScene`: Scene identifier dict with `id` (UUID) and `name` (display name)
    ///
    /// - Parameters:
    ///   - uuid: HomeKit scene UUID for internal identification
    ///   - name: Human-readable scene name (displayed in Shortcuts)
    /// - Returns: Action dictionary for serialization into WFWorkflowActions
    private func sceneAction(uuid: String, name: String) -> [String: Any] {
        return [
            "WFWorkflowActionIdentifier": "is.workflow.actions.homekit.scene",
            "WFWorkflowActionParameters": [
                "WFHomeScene": [
                    "id": uuid,
                    "name": name
                ]
            ]
        ]
    }

    /// Build a delay action (WFWorkflowActionIdentifier: is.workflow.actions.delay).
    ///
    /// Creates a dictionary representing a "Pause" action that pauses execution
    /// for a specified number of seconds. Used to add timing between HomeKit actions,
    /// allowing devices time to respond or preventing rapid-fire commands.
    /// The action parameters include:
    /// - `WFDelayTime`: Number of seconds to pause (int)
    ///
    /// - Parameter seconds: Duration of the pause in seconds
    /// - Returns: Action dictionary for serialization into WFWorkflowActions
    private func delayAction(seconds: Int) -> [String: Any] {
        return [
            "WFWorkflowActionIdentifier": "is.workflow.actions.delay",
            "WFWorkflowActionParameters": [
                "WFDelayTime": seconds
            ]
        ]
    }

    /// Build a comment action (WFWorkflowActionIdentifier: is.workflow.actions.comment).
    ///
    /// Creates a dictionary representing a comment line in the shortcut. Comments do not
    /// perform any action but serve as metadata or documentation within the shortcut.
    /// The action parameters include:
    /// - `WFCommentActionText`: The comment text (string)
    ///
    /// This is used at the start of each generated shortcut to identify it as
    /// HKA-generated, making it easier to recognize and manage these automation shortcuts.
    ///
    /// - Parameter text: The comment text to insert into the shortcut
    /// - Returns: Action dictionary for serialization into WFWorkflowActions
    private func commentAction(_ text: String) -> [String: Any] {
        return [
            "WFWorkflowActionIdentifier": "is.workflow.actions.comment",
            "WFWorkflowActionParameters": [
                "WFCommentActionText": text
            ]
        ]
    }
}
